[tool.poetry]
name = "pixnet-2018"
version = "0.1.0"
description = ""
authors = ["顏孜羲 <joseph.yen@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.6"
flake8 = "^3.5"
autoflake = "^1.2"
isort = "^4.3"

[tool.poetry.dev-dependencies]
